//
// AdditionalData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct AdditionalData: Codable, Hashable {
    public var elevation: String? = "/custom_files/elevation_data"

    public init(elevation: String? = "/custom_files/elevation_data") {
        self.elevation = elevation
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case elevation
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(elevation, forKey: .elevation)
    }
}
