//
// LokiService.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct LokiService: Codable, Hashable {
    public var proxy: String? = "ipc:///tmp/loki"

    public init(proxy: String? = "ipc:///tmp/loki") {
        self.proxy = proxy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case proxy
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(proxy, forKey: .proxy)
    }
}
