//
// MeiliGrid.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct MeiliGrid: Codable, Hashable {
    public var cacheSize: Int? = 100_240
    public var size: Int? = 500

    public init(cacheSize: Int? = 100_240, size: Int? = 500) {
        self.cacheSize = cacheSize
        self.size = size
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cacheSize = "cache_size"
        case size
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cacheSize, forKey: .cacheSize)
        try container.encodeIfPresent(size, forKey: .size)
    }
}
