//
// ServiceLimitsStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ServiceLimitsStatus: Codable, Hashable {
    public var allowVerbose: Bool? = false

    public init(allowVerbose: Bool? = false) {
        self.allowVerbose = allowVerbose
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowVerbose = "allow_verbose"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(allowVerbose, forKey: .allowVerbose)
    }
}
