//
// ServiceLimitsCentroid.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ServiceLimitsCentroid: Codable, Hashable {
    public var maxDistance: Int? = 200_000
    public var maxLocations: Int? = 5

    public init(maxDistance: Int? = 200_000, maxLocations: Int? = 5) {
        self.maxDistance = maxDistance
        self.maxLocations = maxLocations
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxDistance = "max_distance"
        case maxLocations = "max_locations"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxDistance, forKey: .maxDistance)
        try container.encodeIfPresent(maxLocations, forKey: .maxLocations)
    }
}
