//
// Httpd.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct Httpd: Codable, JSONEncodable, Hashable {
    public var service: HttpdService?

    public init(service: HttpdService? = nil) {
        self.service = service
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case service
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(service, forKey: .service)
    }
}
