//
// Logging.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct Logging: Codable, JSONEncodable, Hashable {
    public var color: Bool? = true
    public var fileName: String? = "path_to_some_file.log"
    public var type: String? = "std_out"

    public init(color: Bool? = true, fileName: String? = "path_to_some_file.log", type: String? = "std_out") {
        self.color = color
        self.fileName = fileName
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case color
        case fileName = "file_name"
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(fileName, forKey: .fileName)
        try container.encodeIfPresent(type, forKey: .type)
    }
}
