//
// MeiliMultimodal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct MeiliMultimodal: Codable, JSONEncodable, Hashable {
    public var turnPenaltyFactor: Int? = 70

    public init(turnPenaltyFactor: Int? = 70) {
        self.turnPenaltyFactor = turnPenaltyFactor
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case turnPenaltyFactor = "turn_penalty_factor"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(turnPenaltyFactor, forKey: .turnPenaltyFactor)
    }
}
