//
// Odin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct Odin: Codable, JSONEncodable, Hashable {
    public var logging: Logging?
    public var markupFormatter: OdinMarkupFormatter?
    public var service: OdinService?

    public init(logging: Logging? = nil, markupFormatter: OdinMarkupFormatter? = nil, service: OdinService? = nil) {
        self.logging = logging
        self.markupFormatter = markupFormatter
        self.service = service
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case logging
        case markupFormatter = "markup_formatter"
        case service
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(logging, forKey: .logging)
        try container.encodeIfPresent(markupFormatter, forKey: .markupFormatter)
        try container.encodeIfPresent(service, forKey: .service)
    }
}
