//
// ServiceLimitsPedestrian.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ServiceLimitsPedestrian: Codable, Hashable {
    public var maxDistance: Int? = 250_000
    public var maxLocations: Int? = 50
    public var maxMatrixDistance: Int? = 200_000
    public var maxMatrixLocationPairs: Int? = 2500
    public var maxTransitWalkingDistance: Int? = 10000
    public var minTransitWalkingDistance: Int? = 1

    public init(maxDistance: Int? = 250_000, maxLocations: Int? = 50, maxMatrixDistance: Int? = 200_000, maxMatrixLocationPairs: Int? = 2500, maxTransitWalkingDistance: Int? = 10000, minTransitWalkingDistance: Int? = 1) {
        self.maxDistance = maxDistance
        self.maxLocations = maxLocations
        self.maxMatrixDistance = maxMatrixDistance
        self.maxMatrixLocationPairs = maxMatrixLocationPairs
        self.maxTransitWalkingDistance = maxTransitWalkingDistance
        self.minTransitWalkingDistance = minTransitWalkingDistance
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxDistance = "max_distance"
        case maxLocations = "max_locations"
        case maxMatrixDistance = "max_matrix_distance"
        case maxMatrixLocationPairs = "max_matrix_location_pairs"
        case maxTransitWalkingDistance = "max_transit_walking_distance"
        case minTransitWalkingDistance = "min_transit_walking_distance"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxDistance, forKey: .maxDistance)
        try container.encodeIfPresent(maxLocations, forKey: .maxLocations)
        try container.encodeIfPresent(maxMatrixDistance, forKey: .maxMatrixDistance)
        try container.encodeIfPresent(maxMatrixLocationPairs, forKey: .maxMatrixLocationPairs)
        try container.encodeIfPresent(maxTransitWalkingDistance, forKey: .maxTransitWalkingDistance)
        try container.encodeIfPresent(minTransitWalkingDistance, forKey: .minTransitWalkingDistance)
    }
}
