//
// ServiceLimitsSkadi.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
    import AnyCodable
#endif

public struct ServiceLimitsSkadi: Codable, JSONEncodable, Hashable {
    public var maxShape: Int? = 750_000
    public var minResample: Int? = 10

    public init(maxShape: Int? = 750_000, minResample: Int? = 10) {
        self.maxShape = maxShape
        self.minResample = minResample
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case maxShape = "max_shape"
        case minResample = "min_resample"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(maxShape, forKey: .maxShape)
        try container.encodeIfPresent(minResample, forKey: .minResample)
    }
}
